version: "3"
services:
  frpc:
    image: stilleshan/frpc
    container_name: frpc
    volumes:
      - ./frpc/frpc.ini:/frp/frpc.ini
    restart: always

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 81:80
      - 444:443
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/vhost:/etc/nginx/conf.d/vhost
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/html:/usr/share/nginx/html
    restart: always
